import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/mod/Header";
import Footer from "@/components/mod/Footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} font-sans antialiased flex flex-col overflow-hidden`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
export default RootLayout;

